### ISSUE TITLE
Comments list markup : ul or ol ?

### ISSUE THREAD

**Issue by yoanmalie** [sebastiangreger/kirby3-commentions#119]
Hello, still enjoying the 2.0 beta 2 version 😃.

Since the comments are ordered by their date of post, don't the `<ul>` should be replaced by `<ol>` ?

**Comment by sebastiangreger** [comment]
Great to hear the many bugs you uncovered hasn't taken the joy out of it, yet :wink:.

You are correct, this is a rather opinionated default. As I last researched the ideal HTML semantics of a "comments list", it turned out there are as many opinions as there are HTML tags. `<ul>` vs `<ol>` is one aspect; I even found suggestions to use a `<dl><dt><dd>` markup, or to avoid lists entirely (e.g. the [Indieweb wiki](https://indieweb.org/comments#How_to_markup) suggesting a `<div>` markup instead enhanced by microformats) etc.pp.

Since the `list.php` template is the one most likely to be customized anyways, I'd like to not include excessive config options (it only becomes harder to read for people wanting to modify it), but adding an attribute to the helper call that allows to switch between `ul` and `ol` is easy. I added an option to the helper (call `<?= commentions('list', ['listtype' => 'ol']) ?>` to get the ordered list markup on the `develop` branch and will include this in beta 3.
