### ISSUE TITLE
Possibility of XSS attacks caused by insufficient HTML filtering

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#30]
The plugin currently supports Markdown, as well as HTML formatting in comments and I guess, for compatibility reasons it has to stay this way? I noticed, that we are currently using PHP’s `strip_tags()` function to filter HTML (see 
https://github.com/sebastiangreger/kirby3-commentions/blob/array-to-object/classes/Commention.php#L126), but that does not filter out malicious code hidden in attributes. The following code allows the execution of abitrary JavaScript, once the user moves the mouse cursor just a single pixel.

```html
<b onmouseover="this.style='';alert('js')" style="position: fixed; z-index: 100000; top: 0; left: 0; width: 100%; height: 100%; color: transparent;">Evil</b>
```

As comments need manual moderation by default, this is IMHO not a highly risky thing, but if someone changes the setting to publish comments directly after submission, this security flaw would become very dangerous.

I did some research about what’s the best way of dealing with this. First of all, I would not recommend using the KirbyTags parser for comments, as it might offer more powerful manipulation of the site than plain Markdown. This also means, we should utilize and init the `Parsedown` library directly, so the way of how comments are formatted does not depend in indivudual settings (e.g. I would always enable that line-breaks are converted to `<br>` and not use `ParsedownExtra`), but we should enable smartypants to get things like curly quotes in the style, that the site author has intended:

```php
$parser = new Parsedown();
// $parser->setSafeMode(true);
$parser->setBreaksEnabled(true);
$html = smartypants($parser->text($text));
```

We cannot use Parsedown’s `safeMode` feature, as it would strip out all HTML tags, even harmless ones.

The best solution would IMHO be to use the [HTML Purifier](http://htmlpurifier.org/), as it seems to be the most robust solution available. It allows us to define a very restrictive set of allowed HTML tags and attributes. I would also prefer to handle the plugin’s dependeny management (including other 3rd-party PHP code liek the Mf2 parser) via composer. That will make it much easier to upgrade any of these libraries in the future, if some security issues have been discovered with them. And as Composer would give aus fully-automated autoloading, this would also free us from defining all the includes manually.

@sebastiangreger I really don’t want this project to explode, but as this one could really do harm in the wild, I would rather go the extensive-but-safe route. I can take care of all the things mentioned above, it’s probably not too much work. What do you think?

**Comment by sebastiangreger** [comment]
Very important observations, thank you! This obviously needs fixing.

Just "thinking aloud":

Markdown support is only relevant for comments posted on the site itself, whereas any incoming webmention commonly carries a payload of HTML (as marked up in the `h-entry` of the sending page). We could either have a markdown-to-HTML conversion in `Commentions::sanitize()`, hence any `text` fields in the YAML files would always be HTML (any v0.x legacy content stored in Markdown could be dealt with in the migration script by calling the `sanitize` function), or support the storage of either and take care of it during output. No preference, just stating the - probably - obvious. Generally, I'd assume dealing with one consistent format (HTML, due to webmentions) in the data files is easier?

Ideally, all HTML would already be kept in a safe format, so even somebody building their own output logic could trust on a safe `text` field? We'd never have any critical HTML in the data files.

As for safeguarding the HTML, I personally believe it can be rather restrictive. People vary in their preferences for presenting the HTML of webmentions: some don't present the text at all, others compute an excerpt, others display the full text entry (at least for some formats, maybe not for likes, but e.g. for replies). Still, I assume nobody would want rich a comment section with embedded images etc. So stripping it down to just what is needed to keep them legible (line breaks, paragraphs, potentially some italics/bold/strikethrough etc.) should be sufficient. We likely could weld together the current `strip_tags($html, '<br><p><ul><ol><li><em><strong><i><b><blockquote><q>')` with some logic to strip arguments, but if HTML Purifier does all of that by just calling that library - I'm having a hard time to think why we wouldn't just use that indeed!

So my proposal:
* use Parsedown as per your proposal to render Markdown,
* then purify the HTML (for now with a hardcoded set of settings that we deem appropriate; in the future there could be 2-3 presets of Purifier settings),
...all that maybe best in `Commentions::sanitize()`, so during input, not output?

If you'd wish more input, I could do a quick survey on how other Webmention plugins deal with this?

**Comment by fabianmichael** [comment]
> So my proposal:
> 
>     use Parsedown as per your proposal to render Markdown,
>     then purify the HTML (for now with a hardcoded set of settings that we deem appropriate; in the future there could be 2-3 presets of Purifier settings),

Sounds like a good plan, I would just prefer to ignore the possibility of having multiple settings for now. I also think, that Markdown is way easier to write, at least from my personal experience with GitHub. But I’m probably biased, because I basically use Markdown for all of my personal writing needs as well and barely use a text processor like e.g. LibreOffice at all. As we need the purifier anyway for incoming webmentions and as Parsedown comes with Kirby, I don’t see any reason for not parsing Markdown as well, so it basically works like commenting on GitHub.

>     ...all that maybe best in Commentions::sanitize(), so during input, not output?

This should bring a noticable performance boost for pages with long comment list, as parsing only needs to be sone once and for good for every commention. Downsides are, that the initial payload will get lost and later edits (if the plugin will re-add support for this in the future) could not be done in Markdown. Another possibility could be to store that raw input in `text` and the processed text in e.g. `safe_text`. This would leave the possibility of editing the original input while still giving us the performance benefit of sanitizing in advance. What do you think?

> `If you'd wish more input, I could do a quick survey on how other Webmention plugins deal with this?`

If you want to go this route, I’d be happy to hear the results. But please do it only, if you got the time for that.

**Comment by sebastiangreger** [comment]
> Sounds like a good plan, I would just prefer to ignore the possibility of having multiple settings for now.

Yes, let's keep it simple. We decide what's the policy, and options can be added later it the need arises. That's what I had in mind.

> I also think, that Markdown is way easier to write, at least from my personal experience with GitHub. But I’m probably biased, because I basically use Markdown for all of my personal writing needs as well and barely use a text processor like e.g. LibreOffice at all. As we need the purifier anyway for incoming webmentions and as Parsedown comes with Kirby, I don’t see any reason for not parsing Markdown as well, so it basically works like commenting on GitHub.

So you mean we'd store either or? Works for me, no problem. Just the other way, storing incoming HTML from webmentions as MD is not recommended, as I can tell from painful experiences when I migrated my old blog from WP to Kirby... 

Really: it seems you have a clear idea how to bake this into the plugin, so just go ahead. No need to listen to me brainstorming :wink: 

> This should bring a noticable performance boost for pages with long comment list, as parsing only needs to be sone once and for good for every commention.

Yes, it only appeared to me after reading the Purify docs a moment ago - this is a somewhat expensive process, so it's good to do it only once.

> Downsides are, that the initial payload will get lost and later edits (if the plugin will re-add support for this in the future) could not be done in Markdown. Another possibility could be to store that raw input in `text` and the processed text in e.g. `safe_text`. This would leave the possibility of editing the original input while still giving us the performance benefit of sanitizing in advance. What do you think?

No objections, but I'd prefer to have `text` with the clean version and `text_unsafe` as the raw data (includes an implicit warning to anybody accessing that field, plus using `$commention->text()` returns what can be used safely in frontend?

> > `If you'd wish more input, I could do a quick survey on how other Webmention plugins deal with this?`

Well, the WP plugin appears to - rather obvious - use the sanitization of Wordpress itself, and the IndieWeb wiki generally recommends using a library: https://indieweb.org/xss (no recommendation for PHP, though, so I'd add the Purifier once we have it running successfully). Wiki also links to this https://checkmention.appspot.com/ which may come in handy later for testing :zombie:

**Comment by fabianmichael** [comment]
> So you mean we'd store either or? Works for me, no problem. Just the other way, storing incoming HTML from webmentions as MD is not recommended, as I can tell from painful experiences when I migrated my old blog from WP to Kirby..

The Markdown parser could easily be disabled when `type != comment`. This would mean, that Markdown parsing is only applied to comments, that have been submitted to the site directly, but not for webmentions.

> No objections, but I'd prefer to have text with the clean version and text_unsafe as the raw data (includes an implicit warning to anybody accessing that field, plus using $commention->text() returns what can be used safely in frontend?

Sounds like a good plan, let’s do it like you said. I see a huge advantage in returning safe html by default. If a user still wishes to disable HTMl output, he\*she could easily just pass it through another `strip_tags()` and `htmlspecialchars()` call . Should we call the other field `text_unsafe` or rather `text_raw`?

**Comment by fabianmichael** [comment]
@sebastiangreger I added a separate Sanitizer class, to make the logic behind the HTML Sanitizer/Markdown parser re-usable across the plugin. Maybe we should use it as a collection for all Sanitizer methods.

It currently still sanitizes everything on the fly, but before I move on to caching, I’d like to hear your opinion about my tags whitlist (see https://github.com/sebastiangreger/kirby3-commentions/blob/30-html-sanitize/classes/Sanitizer.php). I decided to go with a rather restrictive set, but collected all "harmless" elements from the HTML spec. I decided to disable most attributes, except a few.

Most important: `<code>` elements can have a `language-*` class, because this is used by Parsedown, when using the block code syntax. `<pre>` can have a class attribute, but it may only have a value of `code`, because Parsdown uses it for code blocks. I decided to exclude most attributes that are usually not used. Especially things like the `cite` attribute, because without further processing it’s just hidden and thus mostly useless. It could be used for including hidden URLs, that are not visible but appear in the source code and should rather be considered harmful.

The smartypants filter is also applied, if enabled in Kirby to enhance typography. I am wondering, if using Kirby’s cache for the safe HTML content of a comment would be a better idea, because changing the config could result in a different result, e.g. is someone decides to disable links after a while or changes smartypants settings. How do you think, we could deal with this?

As you proposed, all external links now have `rel="nofollow noopener noreferrer"` set and I decided to enable them by default. Also, URLs in text are turned into URLs by default, but both can be turned off via config. I’m quite proud that I managed to get through HTML Purifier, because the docs don’t offer a lot of examples and explanation and their forum is offline. But the solution seems to be quite robust and it’s pretty cool, that it supports Markdown and HTML at the same time, like GitHub! :-)

Next step for me will be to add some help text to the message field in the form.

**Comment by fabianmichael** [comment]
BTW: Should we apply `rel="nofollow noopener noreferrer"` to author and source links as well?

**Comment by sebastiangreger** [comment]
Wow. Looks like you took a deep dive into the HTML Purifier library. This is impressive!

> I added a separate Sanitizer class, to make the logic behind the HTML Sanitizer/Markdown parser re-usable across the plugin. Maybe we should use it as a collection for all Sanitizer methods.

Good idea. I'm not sure whether merging the current `Commentions::sanitize()` function into it is advised (if that's what you meant?) - as that function is really more about "just" validating fields. If you have a compelling argument for it, I'm game; otherwise we could keep it like this to avoid complexity? In that case, either the Sanitizer class could be renamed to Purifier or the sanitize() function to validateFields() or something; I lean towards the latter, as my function really does not "sanitize" but checks for integrity. Just to avoid using the same verb for two different processes. But that's internal semantics, not so important.

> It currently still sanitizes everything on the fly, but before I move on to caching, I’d like to hear your opinion about my tags whitlist (see https://github.com/sebastiangreger/kirby3-commentions/blob/30-html-sanitize/classes/Sanitizer.php). I decided to go with a rather restrictive set, but collected all "harmless" elements from the HTML spec. I decided to disable most attributes, except a few.

This is obviously something you spent quite some thinking on (also in combination with Markdown considerations), so I'll keep it short: I don't see any obvious spots where I'd disagree, and it looks like a robust set of tags. Ultimately, the only way to fine-tune this will be by using it. Especially with incoming webmention bodies, time will show is it too restrictive or too loose. So I'll be happy to give more feedback once I have test-migrated my current site, which should give some content for verification.

> Most important: `<code>` elements can have a `language-*` class, because this is used by Parsedown, when using the block code syntax. `<pre>` can have a class attribute, but it may only have a value of `code`, because Parsdown uses it for code blocks.

These are very nice touches - it was a good choice to go with the Purifier dependency rather than writing our own regexes :wink: 

> I decided to exclude most attributes that are usually not used. Especially things like the `cite` attribute, because without further processing it’s just hidden and thus mostly useless. It could be used for including hidden URLs, that are not visible but appear in the source code and should rather be considered harmful.

Yes, keep it to the parts needed for visual representations. No hidden meta data.

> The smartypants filter is also applied, if enabled in Kirby to enhance typography.

Yay!

> I am wondering, if using Kirby’s cache for the safe HTML content of a comment would be a better idea, because changing the config could result in a different result, e.g. is someone decides to disable links after a while or changes smartypants settings. How do you think, we could deal with this?

So you mean the `text` field in the YAML would always contain the unaltered payload, but `$commention->text()` would return a cached, purified version?

This would certainly help to keep the comment files clean (no `text` and `text_unsafe` "duplicates" of the same content) and still deal out only safe HTML. I have no idea how expensive the HTML Purifier operations are - as the cache would likely be built on first page load (especially after it has been emptied for some reason), would that be a very slow load? But I agree with the flexibility of changing settings later - that is a very strong argument for the caching solution. It really keeps the YAML files to "raw data" - nice way to separate the data and output layers.

Thinking of it, that seems to almost be the only way to go about it, as otherwise it would require some update script for existing comments (a bit like the migration assistant) and I have no interest in writing such thing :rofl: 

So I'd say, if performance concerns are not too grave let's go that path. Also it is yet another means to reuse Kirby functionality rather than reinventing the wheel?

> As you proposed, all external links now have `rel="nofollow noopener noreferrer"` set and I decided to enable them by default. Also, URLs in text are turned into URLs by default, but both can be turned off via config.

That is good. Also, regarding your other question: yes, we should add these to the snippets as well. I could look up how the Indieweb community feels about `nofollow` on links to webmention sources, but my personal hunch is that I wouldn't by default want to endorse URLs that other people submit to my site.

> I’m quite proud that I managed to get through HTML Purifier, because the docs don’t offer a lot of examples and explanation and their forum is offline. But the solution seems to be quite robust and it’s pretty cool, that it supports Markdown and HTML at the same time, like GitHub! :-)

I really dig this (and would likely not have come up with it this way myself; not to speak about the skills to implement it so neatly).

> Next step for me will be to add some help text to the message field in the form.

Great. You know best what's possible with this enhancement, so you're predestined to write that paragraph...

Regarding your addition to the Readme: please note that there is already a newer version in branch `40-readme`. As far as I can tell, you merely added just one paragraph, so no problem, but there are a lot of (automated?) formatting changes across the document that make it hard for me to see what happened there? (...and, as I pointed out separately, at least in a few spots broke the content by removing some whitespace)

PS: 
```php
// Use unix line breaks only 🤘
```
🤘

**Comment by fabianmichael** [comment]
> This would certainly help to keep the comment files clean (no text and text_unsafe "duplicates" of the same content) and still deal out only safe HTML. I have no idea how expensive the HTML Purifier operations are - as the cache would likely be built on first page load (especially after it has been emptied for some reason), would that be a very slow load? But I agree with the flexibility of changing settings later - that is a very strong argument for the caching solution. It really keeps the YAML files to "raw data" - nice way to separate the data and output layers.
> 
> Thinking of it, that seems to almost be the only way to go about it, as otherwise it would require some update script for existing comments (a bit like the migration assistant) and I have no interest in writing such thing 🤣

I implemented all the caching logic and used Kirby’s native cache version. Each page gets its own cache entry with an array of escaped texts. If the commentions file is newer than the cache, the cache is rewritten. Could be a bit costly for long lists of commentions, but should be goog-enough for now. Using Kirby’s file cache for storing sanitized HTML aktually makes difference of almost 20 % for my test page, that hold about 6 comments with lots of dirty HTML. This could theoretically be improved later on with more sophisticated cache keys, that also respect configuration. But let’s keep it simple for now. Cool thing about Kirby’s native cache is, that it’s only valid per domain, which is important to determine which links are considered external.

I also wrote an adapter for HTML Purifier to use Kirby’s cache as well, so everything in terms of caching not fully utilizes Kirby’s cache drivers, which means that we also support more advanced caching-solutions like APCU or Redis out-of-the-box, if enabled in config.

> Regarding your addition to the Readme: please note that there is already a newer version in branch 40-readme. As far as I can tell, you merely added just one paragraph, so no problem, but there are a lot of (automated?) formatting changes across the document that make it hard for me to see what happened there? (...and, as I pointed out separately, at least in a few spots broke the content by removing some whitespace)

Please go ahead and override them with your older version. I turned of auto-formatting for the project, thanks for pointing that out. Please give it a try to see if all of the changes work for you. If so, this could be merged pretty soon.

**Comment by fabianmichael** [comment]
I added help and renamed `Purifier` to `Formatter` as the class handles all of our comment formatting needs and not just tidying.

The help text is not generated dynamically, based on the `allowlinks` and `autolinks` options. To make things easier for users, who want to customize the form, I moved the logic for that into a separate snippet (`commentions-form-help.php`). The help is places inside a `<details>` element, so they are hidden by default without requiring additional JavaScript.

Formatting help already looks pretty great in my blog:

![Bildschirmfoto 2020-04-25 um 17 39 07](https://user-images.githubusercontent.com/395617/80284134-d7592880-871c-11ea-92ec-7c6e8e6ce69e.png)

If you don’t have any more remarks, I think #44 can be merged intto `dev`.

**Comment by fabianmichael** [comment]
@sebastiangreger Should we make support for code-related tags (inline code and code blocks) optional, because they are not needed in most contexts and add clutter to the help text?

**Comment by sebastiangreger** [comment]
> Could be a bit costly for long lists of commentions, but should be goog-enough for now. Using Kirby’s file cache for storing sanitized HTML aktually makes difference of almost 20 % for my test page, that hold about 6 comments with lots of dirty HTML. This could theoretically be improved later on with more sophisticated cache keys, that also respect configuration. But let’s keep it simple for now. 

I'm not too worried about the performance at this point, and we can tackle it later, if it becomes an issue.

> I added help and renamed `Purifier` to `Formatter` as the class handles all of our comment formatting needs and not just tidying.

:+1: (the folder `classes/Purifier` still uses the old name and the class name is still `Purifier`, is that on purpose or an oversight?)

> The help text is not generated dynamically, based on the `allowlinks` and `autolinks` options. To make things easier for users, who want to customize the form, I moved the logic for that into a separate snippet (`commentions-form-help.php`). The help is places inside a `<details>` element, so they are hidden by default without requiring additional JavaScript.

Nice feature, and I'd say let's keep it like that for now. We should have a final round of harmonizing settings across the plugin (e.g. I am thinking we could move all settings related to the snippets into an array, to make settings more semantic), which I believe is easiest done once we have everything in place and can evaluate the total number of settings.

**Comment by fabianmichael** [comment]
@sebastiangreger I improved the Fallback parser, by switching from simple HTML entity encoding to `strip_tags()` and now it tries to preserve `<p>` and converts line breaks to <br> Please try out, how good this works with you webmention archive.

I also added a fallback to the textarea to notify the user, that HTML is not allowed. Please take a look at the branch, I think we’re ready to merge #44 for now.

**Comment by sebastiangreger** [comment]
Looks good to me. I'm sure there will be some small adjustments needed with the parsing etc., but that's easy to iron out later through minor fixes.

**Comment by sebastiangreger** [comment]
Closing this, as remaining tasks moved to #55
