### ISSUE TITLE
Add help text to message field about available formatting options

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#31]
The plugin currently does not tell the user about the formatting options available in the message field. We should consider to add a little notice below the field, that says which HTML/Markdown commands are allowed.

@sebastiangreger Is there a specific reason, that link elements (`<a>`) are not allowed at all? How should the plugin deal with external links in general? It’s still possible for the user to include plain URLs within message text, they are just not clickable at the moment …

**Comment by sebastiangreger** [comment]
Yes, the UI will have to be adjusted after we're done with the implementation of the "HTML policy". Let's keep this issue open as a reminder.

> Is there a specific reason, that link elements (`<a>`) are not allowed at all?

Personal preference from when I initially wrote this plugin for my personal use :wink: If presenting links, these should at least have `rel="noreferrer noopener"` attribute for safety (in case somebody adds a `target="_blank"` by JS) and `nofollow` (since it is not an endorsement by the page author). I assume HTML Purify provides the required settings; whether links are stripped or not could be configurable in our plugin (I'm happy to look into this config part once it is in place, if you'd like me to).

**Comment by fabianmichael** [comment]
@sebastiangreger Okay, got that. I will keep an eye on that when adding the HTML Purifier library. But I agree, that links should have the attributes you mentioned above. Configuration of allowed HTML tags would be great, if it does not get too complicated. But if links get these additional attributes for safetly, I don’t see any reason for disallowing them.

**Comment by sebastiangreger** [comment]
> But if links get these additional attributes for safetly, I don’t see any reason for disallowing them.

Agreed :+1: And very easy to further manipulate the plugin's output in the template, if one really wants to strip out links or anything else for whatever reason.

**Comment by fabianmichael** [comment]
@sebastiangreger Closing this, as the help texts have already been added.
