### ISSUE TITLE
Deal with double-submitted webmentions

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#41]
If a user submits the same webmention twice, the plugin will currently pick it up and just process it just like a new webmention. This will likely not happen by accident if webmentions are submitted manually through the form, but there’s a high chance of this to happen, when an autmated system takes care of this on the sender’s side. I haven’t got a chance to review this in details and to consult the Webmentions spec for any advice of how to deal with this. We could consider to display a duplicate-warning in the panel beneah the webmention content.

This is IMHO nothing that’s very urgent to solve, but we should be aware of it and can handle it, once we got through all the more-important stuff.

![Bildschirmfoto 2020-04-24 um 13 14 45](https://user-images.githubusercontent.com/395617/80212683-3db84b00-8638-11ea-9c8a-075c8fd081b6.png)

**Comment by sebastiangreger** [comment]
I'll take care of this one, as I already have most of the spec in my head anyways :) A repeated webmention for the same URL has to be treated as an update. I'll have to figure out a few flows related to that.

**Comment by sebastiangreger** [comment]
This is now technically dealt with: a duplicate webmention is treated as update, as per the spec. 

However, conceptually, one significant issue arises from that: this gives the author of an approved webmention direct access to posting to the receiving website (once a webmention has been approved, an update would go straight to the site). I couldn't really find any reference implementations, nor documented Indieweb discussions, so far. I see two ways to deal with this:

1. an updated webmention is automatically reset to `pending`, showing up in the inbox again
2. we introduce a fourth status (`update`, in addition to `pending`, `approved` and `unapproved`); duplicate webmentions are either updated directly, if the original webmention is still pending or unapproved, but for approved webmentions we instead create a new webmention with status `update` and once that is approved, it overwrites the original with status approved.

The former leads to quirky effects when suddenly comments disappear from the site until the admin understands days/weeks later to visit the inbox. The latter sounds complicated, but would actually be rather straightforward to implement in the backend - it would have to be presented accordingly in the panel section, but that would not be too complicated either; just one more aspect to keep in mind. (Of course we're talking about rabbit holes here: what happens if the admin denies an update? Does it delete the original webmention as well? ...etc.pp. Somewhere we'll have to draw a line :wink:)

@fabianmichael If you think option 2 is worth trying (and you don't have a better option 3 in mind that I didn't think of), I could give it a shot?

As for deletions, I believe there is no need to ask for admin approval; quite the opposite, it is good that webmention senders can withdraw them by themselves (the spec is rather unambiguous on that part, and it's very much in the spirit of data ethics and GDPR). I could add another hook, so admins could write their own notification function, but that's already a rather niche feature.

**Comment by fabianmichael** [comment]
@sebastiangreger Option 2 sounds like the most reasonable thing to do, especially if you’re saying, that its actually rather straightforward to implement in the backend. As both of us seemingly don’t personally need that hook before deletion, I would leave it out for now. It can easily be added later, if someone requests it.

**Comment by sebastiangreger** [comment]
> rather straightforward

Emphasis on _rather_ :wink: ...but I got it to work (PR #43 updated). New flow is as follows:
- If a webmention from source URL already exists, it is
  - immediately updated if the status of the original webmention is other than `approved` (i.e. it is not publicly visible; assumption here: as the admin would anyways have to treat it manually before it shows up on the site, there is no harm in silently updating its content)
  - immediately updated if auto-approval for this type of webmention is `true` (would for example allow an advanced setup where users can immediately update their RSVP-type webmention for an event, but replies with displayed text content require approval)
  - otherwise a new, additional commention with type=update is created (i.e. we end up with the original of status `approved` and the new with status `update`)
- The Panel section displays updates in the inbox view, with options
  - "approve" (which then updates the original webmention with the new data and deletes the update item)
  - and "delete" (which deletes both the update and the original; I don't see an immediate use case for rejecting an update but keeping the - then outdated - original, but admit this is not 100% clear from the UI at the moment)
- If an unapproved update is present, but the original webmention is deleted, the `update` item is deleted as well

This was a bit of a brain teaser, but really showed the power of being able to access the commentions as Kirby objects - so much easier to deal with, thanks to all the inherited methods to filter etc. :heart_eyes:

**Comment by fabianmichael** [comment]
Wow, this sound like a very sophisticated solution! :-)
