### ISSUE TITLE
Idea: Let panel warn, if cronjob was not executed

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#47]
@sebastiangreger I just had the idea, that the cronsob could save the last time, when it was called. If that time was more than a day ago, the panel section could display a warning. Should be easy to implement and would eliminate one of the primary errors sources. What do you think?

**Comment by sebastiangreger** [comment]
This is indeed the most probable setup issue, and completely opaque to the user because it "fails silently" - the queue simply never gets executed.

Could the solution be two-fold?
1. Warn users of a setup issue (cron not executed for over 24h = warning to check setup)
2. Connect the loading of the panel - and/or the "refresh" button - with executing the cron

Thinking this through and trying to figure out an approach, I immediately ran into quite some complexity:

Keeping the "last cron run" timestamp is not difficult; could be a simple timestamp file somewhere. Only question: where, as all plugin data is now in subfolders of pages, with no central storage location? `site/logs/commentions` could be one possibility (Retour for Kirby uses that `logs` path, and I adopted that practice for my Micropub plugin as well), or a hidden file at the site root? (That unresolved discussion about a common practice for plugin storage is creeping back in...) When the panel section is called, it would be necessary to first check that timestamp (easy-peasy) and return an error message - this is 1:1 the same as with the version check.

How could we then call the cron? Triggering the function from within `sections/commentions.php` is not really an option, as its execution can take a minute or so. It would have to be asynchronous. Is it best to trigger that from the panel code, using the URL? (Side note: since that URL would have to contain the cron secret, a frontend user could get access to that secret - which should only be known to the site admin - by looking into the Network traffic.)

On the UI level, it would of course be nice that the cron run triggered on panel load delivers new mentions into the queue listing. However, the list suddenly shifting down after half a minute, as new items appear at its top, could lead to input errors (if a user is just about to open the context menu for an item) and does not seem good UX. Maybe an alert to manually refresh instead, once the cron has finished? (There is no info in the cron's response on whether or not we have new inbox items from the queue, though). Or no automatically triggered cron, but instead a notification that there are unprocessed items and the user has to click "Refresh" manually? Counting the number of pending queue items would not be terribly difficult and could be done in `sections/commentions.php` as the initial `computed` values are fetched.

What's your view on this? A minimum implementation would be the timestamp file. That's very easy and solves your primary conern. We could move anything beyond that to a later version...

**Comment by sebastiangreger** [comment]
Also: if the cron is triggered every time a Commentions panel section is displayed, that would be way too much. I am strongly leaning towards the idea to check on the backend whether there are unprocessed items in the queue and then somehow highlight the "Refresh" button to allow triggering a cron run and subsequent list update manually.

Something like `foreach (site()->index())` and then polling all the `_webmentionqueue.yml` files for unprocessed stuff is not exactly the most performant approach; an alternative could be that our "timestamp" file is only created when the Endpoint class has registered a new incoming request and deleted once the cron has been run. That way we'd have a single file to check whether there are pending webmentions and at the same time that file being older than 24h would indicate that the cron is not set up correctly?

**Comment by fabianmichael** [comment]
@sebastiangreger I would prefer a simple solution for now, as starting from tomorrow I have to return to my regular work schedule. For now, I would prefer to solve the basic issue of just telling users that the cron job did not run. If any stats are stored in `site/logs`, they could IMHO just use separate text files as performance of reading a single file does not really matter. I also think, that the cron warning should always appear, if the cron job did not run, not matter if there are any unprocessed submissions, because it a requirement for running the whole plugin (except for comments) at all.

Everything else, like triggering cron jobs from the can be added later, though. By separating the cron job logic from parsing and processing of incoming webmentions etc. into 2 separate classes, it would be quite easy to trigger processing from the panel API instead of the cron job. When processing mentions from the panel, it could be limited to e.g. processing 2 webmentions at once to avoid long loading times or timeouts. The queue will get shorter with any consecutive request until the queue is completely empty.  But let’s tackle that later on. 😉 The panel section needs some fine-tuning on the midterm anyway, as it currently does not handle API errors in a decent way.

**Comment by sebastiangreger** [comment]
Yes, I'm all for keeping it simple! :slightly_smiling_face:

This issue should be solved with PR #49. I'll create a separate issue for the future development ideas.

**Comment by sebastiangreger** [comment]
Just realized that this alert, as implemented now, is also displayed when the plugin is freshly installed, before the user has run the cronjob for the first time.

Reopening the issue as a note-to-self: this can likely be mitigated by instructing the correct order in the Readme, as well as maybe slightly changing the wording of the warning message.
