### ISSUE TITLE
Template part call alwas shows feedback, form and list

### ISSUE THREAD

**Issue by mrmichalzik** [sebastiangreger/kirby3-commentions#69]
If I use one of the three template parts, for example `commentions('feedback');` like it's described in the readme, the plugin renders allways all three parts. It seems you have to use for example `commentionsFeedback()` to only show the feedback part.

**Comment by sebastiangreger** [comment]
Hi, thanks for your message! This is a bit of a mystery, as I cannot replicate this error - on all my test and production sites, I am using `commentions('feedback')` etc. without issues.

Sorry for stating the obvious, but just to make sure: are you indeed running [v1.0.0-rc.1](https://github.com/sebastiangreger/kirby3-commentions/releases/tag/v1.0.0-rc.1) (version indicated in `composer.json` and `index.php`)? I am asking since `commentionsFeedback()` is the old syntax from the experimental 0.x versions, now deprecated (still working for compatibility but will be removed in an upcoming version) and not mentioned in the current Readme at all?

**Comment by sebastiangreger** [comment]
Ok, I think I found the issue: since we marked the current version as -rc.1 on Packagist (which designates a non-stable version), the composer command as included in the Readme pulls the old "stable" version 0.2.3.

I'll fix this asap, but for now you can get the latest version installed using command `composer require sgkirby/commentions=1.0.0-rc.1` on the CLI instead.

Sorry for the confusion and thank you again for reporting! I'd be glad to hear back whether this fixed your issue?

**Comment by mrmichalzik** [comment]
Yes, I checked the composer.json after your first anwer, and did the upgrade manually. Now it seems to work. Thank you for the quick help!
